version: "3.8"

services:
  frontend:
    build:
      context: .  # Build from the Dockerfile in the current directory
      dockerfile: Dockerfile  # Explicitly specify the Dockerfile
    ports:
      - "80:80"  # Map host port 3001 to container port 80
    restart: always
    networks:
      - app-network

networks:
  app-network: